name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup - initialize JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Setup - Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew build --warning-mode all

    - name: Run - Unit Tests
      run: ./gradlew test --warning-mode all

    #- name: Run - Instrumentation Tests
    #  run: ./gradlew connectedAndroidTest
